set -e
true
true
/mnt/beegfs/home/aubzxk001/shell_work/SPAdes-3.15.4-Linux/bin/spades-hammer /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/corrected/configs/config.info
/home/aubzxk001/miniconda3/bin/python /mnt/beegfs/home/aubzxk001/shell_work/SPAdes-3.15.4-Linux/share/spades/spades_pipeline/scripts/compress_all.py --input_file /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/corrected/corrected.yaml --ext_python_modules_home /mnt/beegfs/home/aubzxk001/shell_work/SPAdes-3.15.4-Linux/share/spades --max_threads 4 --output_dir /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/corrected --gzip_output
true
true
/mnt/beegfs/home/aubzxk001/shell_work/SPAdes-3.15.4-Linux/bin/spades-core /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K21/configs/config.info
/mnt/beegfs/home/aubzxk001/shell_work/SPAdes-3.15.4-Linux/bin/spades-core /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K33/configs/config.info
/mnt/beegfs/home/aubzxk001/shell_work/SPAdes-3.15.4-Linux/bin/spades-core /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K55/configs/config.info
/mnt/beegfs/home/aubzxk001/shell_work/SPAdes-3.15.4-Linux/bin/spades-core /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K77/configs/config.info
/mnt/beegfs/home/aubzxk001/shell_work/SPAdes-3.15.4-Linux/bin/spades-core /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K99/configs/config.info
/mnt/beegfs/home/aubzxk001/shell_work/SPAdes-3.15.4-Linux/bin/spades-core /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K127/configs/config.info
/home/aubzxk001/miniconda3/bin/python /mnt/beegfs/home/aubzxk001/shell_work/SPAdes-3.15.4-Linux/share/spades/spades_pipeline/scripts/copy_files.py /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K127/before_rr.fasta /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/before_rr.fasta /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K127/assembly_graph_after_simplification.gfa /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/assembly_graph_after_simplification.gfa /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K127/final_contigs.fasta /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/contigs.fasta /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K127/first_pe_contigs.fasta /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/first_pe_contigs.fasta /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K127/strain_graph.gfa /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/strain_graph.gfa /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K127/scaffolds.fasta /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/scaffolds.fasta /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K127/scaffolds.paths /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/scaffolds.paths /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K127/assembly_graph_with_scaffolds.gfa /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/assembly_graph_with_scaffolds.gfa /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K127/assembly_graph.fastg /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/assembly_graph.fastg /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/K127/final_contigs.paths /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/contigs.paths
true
/home/aubzxk001/miniconda3/bin/python /mnt/beegfs/home/aubzxk001/shell_work/SPAdes-3.15.4-Linux/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/scaffolds.fasta --misc_dir /mnt/beegfs/home/aubzxk001/shell_work/assembly_out$/misc --threshold_for_breaking_scaffolds 3
true
